image: docker:latest
services:
  - name: docker:dind
    alias: dockerdind

variables:
#  DOCKER_DRIVER: overlay2
  SPRING_PROFILES_ACTIVE: production
  USER_GITLAB: root
  APP_NAME: service-discovery
  REPO: logic1/service-discovery

stages:
  - build
  - test
  - develop
  - release
  - production

build:
  image: registry.becopay.com/devops/mvn-docker:latest
  stage: build
  tags:
  - ir
  cache:
    paths:
      - .m2/
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  script:
  - mvn --version
  - mvn package -B
  - ls -alsh target/*.jar
  artifacts:
    paths:
      - target/*.jar
  except:
  - /^feature.*$/

test:
  stage: test
  cache:
    paths:
      - target/
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  script:
  - echo "TEST PASS"

test2:
  stage: test
  cache:
    paths:
      - target/
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  script:
  - echo "TEST 2 PASS CI TEST 2"


develop develop:
  stage: develop
  script:
  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
  - docker build -t registry.becopay.com/logic1/service-discovery/develop:latest .
  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
  - docker push registry.becopay.com/logic1/service-discovery/develop:latest
  only:
  - develop

release:
  stage: release
  script:
  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
  - docker build -t registry.becopay.com/logic1/service-discovery/release:latest .
  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
  - docker push registry.becopay.com/logic1/service-discovery
  only:
  - /^release.*$/

sandbox:
  stage: production
  script:
  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
  - docker build -t registry.becopay.com/logic1/service-discovery/sandbox:latest .
  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
  - docker push registry.becopay.com/logic1/service-discovery
  only:
  - /^master.*$/

production:
  stage: production
  script:
  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
  - docker build -t registry.becopay.com/logic1/service-discovery/production:latest .
  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
  - docker push registry.becopay.com/logic1/service-discovery
  only:
  - /^master.*$/
  when: manual