server:
  port: 8761 # Indicate the default PORT where this service will be started

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false	#telling the server not to register himself in the service registry
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0 #wait time for subsequent sync
    eviction-interval-timer-in-ms: 1000

application:
  clients:
    - username: discovery
      password: becopaydiscovery1234
      roles: client