server:
  port: 8761 # Indicate the default PORT where this service will be started
  ssl:
    enabled: true
    key-store: classpath:eureka.jks
    key-store-password: hpf9$A3FTN
    trust-store: classpath:eureka.jks
    trust-store-password: hpf9$A3FTN
    key-alias: eureka


eureka:
  client:
    registerWithEureka: false	#telling the server not to register himself in the service registry
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0	#wait time for subsequent sync